//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public ALUMNO()
        {
            this.ALUMNO_ANTECEDENTE = new HashSet<ALUMNO_ANTECEDENTE>();
            this.MORA = new HashSet<MORA>();
            this.RESULTADO_ACADEMICO = new HashSet<RESULTADO_ACADEMICO>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_ALUMNO { get; set; }
        public string ID_TRIBUTARIO { get; set; }
        public string NOMBRES { get; set; }
        public string A_PATERNO { get; set; }
        public string A_MATERNO { get; set; }
        public System.DateTime FECHA_NAC { get; set; }
        public string TELEFONO_MOVIL { get; set; }
        public string TELEFONO_HOGAR { get; set; }
        public string EMAIL { get; set; }
        public string ACTIVO { get; set; }
        public string DIRECCION { get; set; }
        public decimal ID_CIUDAD { get; set; }
    
        public virtual ICollection<ALUMNO_ANTECEDENTE> ALUMNO_ANTECEDENTE { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<MORA> MORA { get; set; }
        public virtual ICollection<RESULTADO_ACADEMICO> RESULTADO_ACADEMICO { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
