//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANFITRION
    {
        public ANFITRION()
        {
            this.ANFITRION_ANTECEDENTE = new HashSet<ANFITRION_ANTECEDENTE>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_ANFITRION { get; set; }
        public string ID_TRIBUTARIO { get; set; }
        public string NOMBRES_RESPONSABLE { get; set; }
        public string A_PATERNO_RESPONSABLE { get; set; }
        public string A_MATERNO_RESPONSABLE { get; set; }
        public System.DateTime FECHA_NAC { get; set; }
        public string TELEFONO_MOVIL { get; set; }
        public string TELEFONO_HOGAR { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string ESTADO_ANTECEDENTES { get; set; }
        public decimal CUPOS_ALOJAMIENTO { get; set; }
        public System.DateTime FECHA_ANTECEDENTES { get; set; }
        public decimal ID_CIUDAD { get; set; }
    
        public virtual ICollection<ANFITRION_ANTECEDENTE> ANFITRION_ANTECEDENTE { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
