//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALUMNO> ALUMNO { get; set; }
        public DbSet<ANFITRION> ANFITRION { get; set; }
        public DbSet<ANTECEDENTE> ANTECEDENTE { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<ESTABLECIMIENTO> ESTABLECIMIENTO { get; set; }
        public DbSet<MORA> MORA { get; set; }
        public DbSet<NOTA> NOTA { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PROGRAMA> PROGRAMA { get; set; }
        public DbSet<RAMO> RAMO { get; set; }
        public DbSet<RESULTADO_ACADEMICO> RESULTADO_ACADEMICO { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<ALUMNO_ANTECEDENTE> ALUMNO_ANTECEDENTE { get; set; }
        public DbSet<ANFITRION_ANTECEDENTE> ANFITRION_ANTECEDENTE { get; set; }
        public DbSet<PROGRAMA_ANTECEDENTE> PROGRAMA_ANTECEDENTE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
