//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.ALUMNO = new HashSet<ALUMNO>();
            this.ANFITRION = new HashSet<ANFITRION>();
            this.ESTABLECIMIENTO = new HashSet<ESTABLECIMIENTO>();
        }
    
        public decimal ID_CIUDAD { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_PAIS { get; set; }
    
        public virtual ICollection<ALUMNO> ALUMNO { get; set; }
        public virtual ICollection<ANFITRION> ANFITRION { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<ESTABLECIMIENTO> ESTABLECIMIENTO { get; set; }
    }
}
