//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORA
    {
        public decimal ID_MORA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_ALUMNO { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
    }
}
