//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA
    {
        public decimal ID_NOTA { get; set; }
        public decimal NOTA1 { get; set; }
        public decimal ID_RESULTADO { get; set; }
    
        public virtual RESULTADO_ACADEMICO RESULTADO_ACADEMICO { get; set; }
    }
}
