//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAMO
    {
        public RAMO()
        {
            this.RESULTADO_ACADEMICO = new HashSet<RESULTADO_ACADEMICO>();
            this.PROGRAMA = new HashSet<PROGRAMA>();
        }
    
        public decimal ID_RAMO { get; set; }
        public string SIGLAS_RAMO { get; set; }
        public string NOMBRE_CURSO { get; set; }
        public decimal CUPOS_DISPONIBLES { get; set; }
        public decimal VALOR_CREDITO { get; set; }
        public decimal CUPOS_INICIALES { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<RESULTADO_ACADEMICO> RESULTADO_ACADEMICO { get; set; }
        public virtual ICollection<PROGRAMA> PROGRAMA { get; set; }
    }
}
