//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string ID_REGISTRO { get; set; }
        public decimal ID_ROL { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
